# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET Build and Test

on:
  push:
    branches: [ "masterv2" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'api/.**'
      - 'WebApplication1/.**'
  pull_request:
    branches: [ "masterv2" ]
    paths:
      - 'src/**'
      - 'tests/**'
      - 'api/.**'
      - 'WebApplication1/.**'
  workflow_call:
    
jobs:
  dotnet-format:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Format
      run: dotnet format --verify-no-changes --verbosity diagnostic

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 7.0.x
        dotnet-quality: 'ga'
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --nologo
    - name: UnitTests
      run: dotnet test --filter 'FullyQualifiedName!~ApiTests' --no-restore --nologo
